### ISSUE TITLE
Rozlišení chyb docker bundle od (internal) chyb v komponentách 

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#64]
Rád bych to hlavního monitoringu posílal jenom samotné chyby docker bundle a chyby z komponent někam vedle.

Tohle je chyba uvnitř komponenty:
```
message: Application error: Container 'builder-dca-custom-science-python-192071679-5763be486b2d5' failed: (2) 'Contents'
Traceback (most recent call last):
  File "/home/main.py", line 108, in <module>
    downloadData(current_prefix,  ... nloadData
    for key in 
level: 500
component: dca-custom-science-python
app: docker
job: {
id: 192071678
}
cliCommand: /www/syrup-router/components/docker/releases/20160610113516/vendor/keboola/syrup/app/console syrup:run-job 192071678 --env=prod
runId: 192071679
pid: 25655
priority: CRITICAL
token: {
id: 54377
description: genta@traveloka.com
owner: {
id: 1218
name: Traveloka
}
}
exceptionId: docker-fbce9b197372135bc04a06e8dcb744f0
exception: {
class: Keboola\Syrup\Exception\ApplicationException
message: Application error: Container 'builder-dca-custom-science-python-192071679-5763be486b2d5' failed: (2) 'Contents'
Traceback (most recent call last):
  File "/home/main.py", line 108, in <module>
    downloadData(current_prefix,  ... nloadData
    for key in client.list_objects(Bucket=bucket, Prefix=prefix, MaxKeys=1000000)['Contents']:
KeyError: 'Contents'
code: 0
attachment: https://connection.keboola.com/admin/utils/logs?file=2016/06/17/2016-06-17-11-09-34-5763be4ed4beb-exception
}
attachment: https://connection.keboola.com/admin/utils/logs?file=2016/06/17/2016-06-17-11-09-34-5763be4edf828-log
}
```

Tohle je chyby docker bundle:
```
message: Application error: Container 'quay.io/keboola/gmail-extractor:1.0.1' failed: (125) docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container did not start before the specified timeout".
level: 500
component: keboola.ex-gmail
app: docker
job: {
id: 192005551
}
cliCommand: /www/syrup-router/components/docker/releases/20160610113516/vendor/keboola/syrup/app/console syrup:run-job 192005551 --env=prod
runId: 192005535.192005552
pid: 8885
priority: CRITICAL
token: {
id: 53149
description: Orchestrator passed builds
owner: {
id: 1118
name: Vlado Redshift
}
}
exceptionId: docker-ea4a812ab4edcbbf9d34b27a3ed36a70
exception: {
class: Keboola\Syrup\Exception\ApplicationException
message: Application error: Container 'quay.io/keboola/gmail-extractor:1.0.1' failed: (125) docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container did not start before the specified timeout".
code: 0
attachment: https://connection.keboola.com/admin/utils/logs?file=2016/06/17/2016-06-17-02-01-04-57633dc072eac-exception
}
```

A stejně i chyba která nastane v PHP kodu docker bundle.

**Comment by odinuv** [comment]
nove maji eventy z docker-runner  `app: docker-core` a eventy z containeru maji `app: docker`. Problem je, ze kdyz container spadne s error=2, tak to hodime jako ApplicationException https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L329 a tu zaloguje syrup automaticky jako chybu komponenty https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L250 a timpadem je u ni zase `docker-core`. 

Napada me tady https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L329 vymenit message za generickou a vyhodit to jako UserException. K tomu by tam ale asi melo byt ` $exceptionId = $this->logException('critical', $e);` aby se to zalogovalo se spravnym levelem (protoze syrup uz to neudela https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L223) 

A taky nevim jestli na neco bude mit rozdil mezi tim, z UserException vrati Success https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L230 a ApplicationException vrati error https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L265

**Comment by Halama** [comment]
Ještě mě napadlo jestli bysme nemohli docker bundle nastavit tak at výstup (eventy) od kontejnerů vůbec neposílá do PT?

**Comment by ondrejhlavacek** [comment]
plus by bylo dobrý, aby se app/user chyby ještě logovaly tak, aby k nim měl vývojář komponenty přístup

**Comment by odinuv** [comment]
vystup od kontejneru se do PT posilat nemusi, ale kam ho teda budeme posilat?

**Comment by Halama** [comment]
jde preci do SAPI event a to imho staci? je to log pro uzivatele ktery tu komponentu spustil.

**Comment by ondrejhlavacek** [comment]
vývojář v projektu vůbec být nemusí a k chybě by se měl dostat

**Comment by ondrejhlavacek** [comment]
psal jsem vývojáře, ne usera :-)

**Comment by Halama** [comment]
nepsal jsem o chybach ale info eventech

**Comment by odinuv** [comment]
no tak to je vec syrupu, chova se to jako vsechny ostatni komponenty - tj. co jde do sapi jde i do pt a imho je to tak dobre

**Comment by Halama** [comment]
j to vim, me treba ty info eventy prave od komponent prave spis otravuji

**Comment by odinuv** [comment]
no myslim, ze se to reislo tak pred rokem a nakonec vyhralo to, ze je dobry v PT videt vsechno, nez se snazit slepit dve disjunktni mnozinty eventu ze sapi a z pt

**Comment by Halama** [comment]
ale nektery jsou zas dulezity, to je prave to co mi na tom vadilo od zacatku, ze je sjednocene logovani do PT se sapi eventama, i kdyz jde o uplne rozdilne logy k jinym ucelum.

**Comment by odinuv** [comment]
kazdopadne bych tohle resil stejne pro vsechy komponenty - tj na urovni syrupu

**Comment by Halama** [comment]
ok, neresme to ted tady, sorry za offtopic

**Comment by odinuv** [comment]
obsolete
